global:
	scrape_interval: 15s
	evaluation_interval: 15s

scrape_configs:
	- job_name: 'prometheus'
		static_configs:
			- targets: ['localhost:9090']

	- job_name: 'backend'
		metrics_path: /metrics
		static_configs:
			- targets: ['backend:8000']

	- job_name: 'mosquitto'
		metrics_path: /metrics
		static_configs:
			- targets: ['mosquitto-exporter:9150']

	- job_name: 'node_exporter'
		static_configs:
			- targets: ['node-exporter:9100']

	- job_name: 'cadvisor'
		static_configs:
			- targets: ['cadvisor:8080']

	- job_name: 'frontend'
		metrics_path: /metrics
		static_configs:
			- targets: ['frontend:3000']

	- job_name: 'celery'
		metrics_path: /metrics
		static_configs:
			- targets: ['celery:5555']

rule_files:
	- 'alert.rules.yml'
